/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AkarIcon {
        "cap": string;
        "color": string;
        "join": string;
        "name": string;
        "size": number;
        "stroke": number;
    }
}
declare global {
    interface HTMLAkarIconElement extends Components.AkarIcon, HTMLStencilElement {
    }
    var HTMLAkarIconElement: {
        prototype: HTMLAkarIconElement;
        new (): HTMLAkarIconElement;
    };
    interface HTMLElementTagNameMap {
        "akar-icon": HTMLAkarIconElement;
    }
}
declare namespace LocalJSX {
    interface AkarIcon {
        "cap"?: string;
        "color"?: string;
        "join"?: string;
        "name"?: string;
        "size"?: number;
        "stroke"?: number;
    }
    interface IntrinsicElements {
        "akar-icon": AkarIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "akar-icon": LocalJSX.AkarIcon & JSXBase.HTMLAttributes<HTMLAkarIconElement>;
        }
    }
}
